version: '3.1'

services:

  app: 
    build: ./
    restart: unless-stopped
    container_name: node-wallets
    environment:
      - ETHERSCAN_APIKEY=NSZCD6S4TKVWRS13PMQFMVTNP6H7NAGHUY
      - NODE_LOCAL_PORT=8080
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/securitize_wallets?schema=public
    ports:
      - 80:6868
    command: /bin/sh -c "npx prisma migrate deploy && npm run start:prod"
    stdin_open: true
    tty: true
    
