version: '3.1'

services:

  app: 
    build: ./
    restart: unless-stopped
    container_name: node-wallets
    environment:
      - ETHERSCAN_APIKEY=""
      - NODE_LOCAL_PORT=8080
      - DATABASE_URL=""
    ports:
      - 80:8080
    command: /bin/sh -c "npx prisma migrate deploy && npm run start:prod"
    stdin_open: true
    tty: true
    
